// This file is generated by the rust-axum-template setup.sh script.
// It is designed as a dynamic way of hard-coding the app prefix for env vars.

// If you are trying to do this by hand, you need to have something like this:
//
// /// app_conf_root macro hard-codes the app prefix:
// macro_rules! app_conf_root {
//     ($(#[$meta:meta])* $vis:vis struct $name:ident $body:tt) => {
//         $(#[$meta])*
//         #[derive(Conf, Debug, Clone, serde::Serialize, serde::Deserialize)]
//         #[conf(serde, env_prefix = "MY_APP_")]
//         $vis struct $name $body
//     };
// }

/// app_conf_root macro hard-codes the app prefix:
#[macro_export]
macro_rules! app_conf_root {
    ($(#[$meta:meta])* $vis:vis struct $name:ident $body:tt) => {
        $(#[$meta])*
        #[derive(Conf, Debug, Clone, serde::Serialize, serde::Deserialize)]
        #[conf(serde, env_prefix = "AXUM_DEV_")]
        $vis struct $name $body
    };
}
